apiVersion: v1
kind: Secret
metadata:
  name: caipe-ui-secret
  namespace: ai-platform-engineering
  labels:
    app.kubernetes.io/name: caipe-ui
    app.kubernetes.io/component: ui
stringData:
  NEXTAUTH_SECRET: "change-me"
  CAIPE_UI_OIDC_ENABLED: "false"
  CAIPE_UI_OIDC_CLIENT_ID: ""
  CAIPE_UI_OIDC_CLIENT_SECRET: ""
  CAIPE_UI_OIDC_ISSUER: ""
